name: Update

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: git clone 'https://github.com/Terachan0117/covid19-toyama.git'
