name: Update

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get open data
      run: curl -X GET -d {} 'http://opendata.pref.toyama.jp/api/3/action/package_show?id=covid19'
